Find the Difference
********************
  You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

  Code
  ****
  class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        count_s, count_t=Counter(s), Counter(t)
        for c in (count_t):
            if c not in count_s:
                return c
            if count_s[c]<count_t[c]:
                return c
Example 1:
*********
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:
*********
Input: s = "", t = "y"
Output: "y"
 
